PruebaArtistas.Web/Models/ErrorViewModel.cs
namespace PruebaArtistas.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PruebaArtistas.Web/Controllers/CantanteController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaArtistas.Data.Entidades;
using PruebaArtistas.Logica;

namespace PruebaArtistas.Web.Controllers
{
    public class CantanteController : Controller
    {
        private ICantanteService _CantanteSErvice;

        public CantanteController(ICantanteService CantanteSErvice)
        {
            _CantanteSErvice = CantanteSErvice;
        }
        public IActionResult ListarCantantes()
        {
            return View(_CantanteSErvice.getCantantes());
        }
        [HttpGet]
        public IActionResult AgregarCantante()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AgregarCantante(Cantante cantante)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _CantanteSErvice.InsertCantante(cantante);
            return RedirectToAction("ListarCantantes");
        }
    }
}

PruebaArtistas.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaArtistas.Web.Models;
using System.Diagnostics;

namespace PruebaArtistas.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PruebaArtistas.Web/Views/Cantante/AgregarCantante.cshtml
@model PruebaArtistas.Data.Entidades.Cantante;

<h1>Agregar nuevo cantante: </h1>

<form action="AgregarCantante" method="POST" enctype="multipart/form-data">
    <div>
        Nombre : <input type="text" name="Nombre" asp-for="Nombre" />
        <span asp-validation-for="Nombre"></span>
    </div>
    <div>
        Edad : <input type="number" name="Edad" asp-for="Edad" />
        <span asp-validation-for="Edad"></span>
    </div>
    <div>
        Descripcion : <textarea name="Descripcion" asp-for="Descripcion" ></textarea>
        <span asp-validation-for="Descripcion"></span>
    </div>
    <div>
        <input type="submit" value="Agregar" />
    </div>
</form>

PruebaArtistas.Web/Views/Cantante/ListarCantantes.cshtml
@model List<PruebaArtistas.Data.Entidades.Cantante>

<h1>Tus Cantantes</h1>

@foreach (var item in Model)
{
    <h2>@item.Nombre</h2>
    <h3>@item.Edad</h3>
    <p>@item.Descripcion</p>
}

PruebaArtistas.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PruebaArtistas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaArtistas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PruebaArtistas.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="img/logotype.png"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cantante" asp-action="ListarCantantes">Mis Cantantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cantante" asp-action="AgregarCantante">Agregar Cantante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PruebaArtistas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>